# Generated by Django 5.2 on 2025-04-30 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.DecimalField(auto_created=True, decimal_places=0, max_digits=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('category', models.TextField()),
                ('condition', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.DecimalField(auto_created=True, decimal_places=0, max_digits=100, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[(-1, 'отклонена'), (1, 'принята'), (0, 'ожидает')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='barter.ad')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='barter.ad')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
