# Generated by Django 5.2 on 2025-05-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name_plural': 'Ads'},
        ),
    ]
