# Generated by Django 5.2 on 2025-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0002_alter_ad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
