# Generated by Django 5.2 on 2025-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0003_alter_ad_id_alter_exchangeproposal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[(-1, 'отклонена'), (1, 'принята'), (0, 'ожидает')], default=0),
        ),
    ]
